version: '3.8'
services:
  innoscripta-blog:
    build: .
    ports:
      - "80:80"
    environment:
      - VITE_GUARDIAN_API_KEY=${GUARDIAN_API_KEY}
      - VITE_NYT_API_KEY=${NYT_API_KEY}
      - VITE_NEWS_API_KEY=${NEWS_API_KEY} 