version: '3.8'
services:
  innoscripta-blog:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      VITE_GUARDIAN_API_KEY: ${VITE_GUARDIAN_API_KEY}
      VITE_NYT_API_KEY: ${VITE_NYT_API_KEY}
      VITE_NEWS_API_KEY: ${VITE_NEWS_API_KEY}
    command: pnpm dev -- --host 